services:
  postgres:
    image: postgres:16-alpine
    container_name: finux-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=en_US.UTF-8"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finux-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-faliux} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  migrate:
    image: kukymbr/goose-docker:3.26.0
    container_name: finux-migrator
    volumes:
      - ./scripts/migrations:/migrations
    networks:
      - finux-network
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "host=postgres user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    command: goose up

networks:
  finux-network:
    driver: bridge

volumes:
  postgres_data:
